#!/usr/bin/env python3
"""
Parser script to convert vocabulary.txt to vocabulary.js
Format: Chapter Title, '+++', '[KEY]Key Sentence', '---', then 'word|pos|meaning|example'
"""

def parse_vocabulary_file(input_file, output_file):
    """Parse vocabulary.txt and generate vocabulary.js with window.VOCAB_DATA"""
    chapters = []
    
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Split by chapter (using +++ as delimiter)
    chapter_blocks = content.strip().split('\n+++\n')
    
    for i, block in enumerate(chapter_blocks):
        if not block.strip():
            continue
        
        # For first block, it's just the title
        # For subsequent blocks, we need to get the title from previous block
        if i == 0:
            # First block is just a title, skip it
            # We'll use it with the next block
            continue
        
        # Get chapter title from previous block (or use a default)
        chapter_title = chapter_blocks[i-1].strip() if i > 0 else "Untitled"
        
        lines = block.strip().split('\n')
        if len(lines) < 2:
            continue
        
        # First line should contain [KEY] sentence
        key_sentence = ""
        vocab_start_idx = 0
        
        if lines[0].startswith('[KEY]'):
            key_sentence = lines[0].replace('[KEY]', '').strip()
            vocab_start_idx = 1
        
        # Find the --- separator
        separator_idx = -1
        for j in range(vocab_start_idx, len(lines)):
            if lines[j].strip() == '---':
                separator_idx = j
                break
        
        if separator_idx == -1:
            continue
        
        # Parse vocabulary entries (after ---)
        words = []
        for j in range(separator_idx + 1, len(lines)):
            line = lines[j].strip()
            if not line:
                continue
            
            parts = line.split('|')
            if len(parts) >= 4:
                words.append({
                    'word': parts[0].strip(),
                    'pos': parts[1].strip(),
                    'meaning': parts[2].strip(),
                    'example': parts[3].strip()
                })
        
        chapters.append({
            'title': chapter_title,
            'key_sentence': key_sentence,
            'words': words
        })
    
    # Generate vocabulary.js
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated from vocabulary.txt by parser.py\n')
        f.write('// Do not edit this file directly\n\n')
        f.write('window.VOCAB_DATA = ')
        
        # Write JSON data
        import json
        f.write(json.dumps(chapters, indent=2, ensure_ascii=False))
        f.write(';\n')
    
    print(f'Successfully parsed {len(chapters)} chapter(s) with {sum(len(ch["words"]) for ch in chapters)} words total.')
    print(f'Output written to {output_file}')


if __name__ == '__main__':
    parse_vocabulary_file('vocabulary.txt', 'vocabulary.js')
