// Auto-generated from vocabulary.txt by parser.py
// Do not edit this file directly

window.VOCAB_DATA = [
  {
    "title": "Sentence 04",
    "key_sentence": "There is considerable debate about whether we should be attempting to contact life forms from an alien civilisation.",
    "words": [
      {
        "word": "considerable",
        "pos": "adj.",
        "meaning": "important or large enough to be noticed",
        "example": "The project requires a considerable amount of time and effort."
      },
      {
        "word": "debate",
        "pos": "n.",
        "meaning": "a discussion involving different opinions",
        "example": "The debate about climate change continues in parliament."
      },
      {
        "word": "attempt",
        "pos": "v.",
        "meaning": "to try to do something",
        "example": "Scientists attempt to find evidence of life on other planets."
      },
      {
        "word": "contact",
        "pos": "v.",
        "meaning": "to communicate with someone",
        "example": "We should contact the authorities if we see anything suspicious."
      },
      {
        "word": "civilisation",
        "pos": "n.",
        "meaning": "an advanced state of human society",
        "example": "Ancient civilisations built remarkable structures."
      },
      {
        "word": "alien",
        "pos": "adj.",
        "meaning": "belonging to a foreign country or race; strange",
        "example": "The concept seemed alien to most people at first."
      }
    ]
  }
];
